-- Add search_keywords column to themes table
-- This column stores a JSON array of keywords that scanners should use to search for content
-- Example: ["kubernetes", "k8s", "container orchestration", "pods", "deployments", ...]

ALTER TABLE themes 
ADD COLUMN IF NOT EXISTS search_keywords TEXT;

-- Add comment explaining the search keywords feature
COMMENT ON COLUMN themes.search_keywords IS 'JSON array of search keywords for this theme. Scanners use these keywords instead of just the theme name to find more relevant content. Generated by LLM when theme is created or regenerated via API.';

-- Create index for full-text search on keywords (if using PostgreSQL full-text search)
-- Note: This is optional and depends on your search strategy
-- CREATE INDEX IF NOT EXISTS idx_themes_search_keywords ON themes USING GIN (to_tsvector('english', search_keywords));

