-- Add tags column to topics table
-- Tags are used to categorize topics and clusters for better organization

ALTER TABLE topics 
ADD COLUMN IF NOT EXISTS tags TEXT;

-- Create index for tag search (using GIN index for JSON array search)
-- Note: This assumes tags are stored as JSON array
-- If using PostgreSQL 12+, can use jsonb for better performance
CREATE INDEX IF NOT EXISTS idx_topics_tags ON topics USING gin(to_tsvector('english', tags));

-- Add comment explaining the tags feature
COMMENT ON COLUMN topics.tags IS 'JSON array of tags for categorizing topics. Tags help organize topics and clusters into categories (e.g., ["tutorial", "beginner", "kubernetes", "networking"]). Generated by LLM during topic processing.';
